### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by samuelbelko** [samuelbelko/GSoC-playground#2]
Critical tasks:

- [ ] numerical stability tricks: see `compute_lengths`, `update_TR!` methods in `TurboTR.jl` and `merge_with_tr_defaults` in `Turbo.jl`
- [ ]  hyperparmeter optimization: compute initializer for optimization from data, restart optimization with different initial points

High priority:

- [ ] in `Turbo.jl`, check if evaluation budget is enough for evaluating init. samples
- [ ] add input checks via exceptions and assertions
- [ ] add tests
- [ ] document internal flow / interfaces

Nice to have, but not necessary for the first version:

- [ ] `turbo_policy_seq` in `TurboPolicy.jl`: more research on the use of Sobol sequences, how many initial samples to skip? (cf. `Turbo` constructor)
- [ ] extend `OptimizationHelper`: add verbosity levels, measure duration
- [ ] `TurboPolicy`: allow to configure candidate_size
- [ ] make initial sampler a parameter of `Turbo` in `Turbo.jl` 

Possible future features:

- [ ] noisy observations: in `TurboTR.jl` set center of a TR to maximum posterior mean?
- [ ] add traditional BO with GPs `DecisionSupportModel` in `BasicGP.jl`
- [ ] Ask-tell interface, cf. comment in 'SurrogateOptimizationDemo.jl`

Experiments:

- [ ] try different surrogates for `Turbo` algorithm from `Surrogates.jl`
